# Generated by Django 4.2.30 on 2026-05-06 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBooks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('checked_out_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Users Books',
                'db_table': 'users_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='home_book_title_7292c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user'], name='home_checko_user_id_4d82f7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['book'], name='home_checko_book_id_1fbc87_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_checkout'),
        ),
    ]
