# Generated by Django 6.0.4 on 2026-05-04 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.RunSQL(
            sql=""" 
            CREATE OR REPLACE VIEW users_books AS  
            SELECT  
                ROW_NUMBER() OVER (ORDER BY hc.id) AS id,
                hc.checked_out_at, 
                b.title, 
                hc.user_id
            FROM  
            home_book b  
            JOIN  
            home_checkout hc ON b.id = hc.book_id;
                """,
            reverse_sql="DROP VIEW IF EXISTS users_books;"
        )

    ]
