# Generated by Django 6.0.4 on 2026-05-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_users_books_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('checked_out_at', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Users Books',
                'db_table': 'users_books',
                'managed': False,
            },
        ),
    ]
