# Generated by Django 4.2.30 on 2026-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usersbooks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='home_book_title_7292c8_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user'], name='home_checko_user_id_4d82f7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['book'], name='home_checko_book_id_1fbc87_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_checkout'),
        ),
    ]
