# Generated by Django 4.2.30 on 2026-05-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_book_available_remove_book_checked_out_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
